Make figure3
meyer-lab/longitudinalSerology pull request #24
Opened 2022-01-27 01:22 UTC by murphymadeleine21

Looks pretty nice. @cyrillustan check out this thread: https://asmlab.slack.com/archives/C01CJV8SH2S/p1643243773015000

2022-01-27 04:27 UTC, aarmey requested changes
Looks like you got an error from the cross-validation splitting in such a way that one class was completely missing in the training set. Are you sure the folds are shuffled and that you're using 10 folds? How many cases are there of severe and deceased? This outcome should be very unlikely unless there are few cases of one class, or the folds aren't shuffled.

2022-01-27 20:11 UTC, murphymadeleine21 commented on syserol/COVID.py
>      kf = KFold(n_splits=10, shuffle=True)
Hm. That's weird. I mean we're very clearly here setting it to a 10 fold split with shuffling.

2022-01-27 20:13 UTC, murphymadeleine21 commented
There is an inbalance between the number of severe vs. deceased patients, but not enough that we would ever have a training set where there are none of the smaller set. We have 35 Deceased patients and 76 Severe, and the training sets are all 99 or 100 in size.

2022-01-27 20:16 UTC, murphymadeleine21 commented
Oh, though the error is saying there's only one type present in the y_true, so seems like it's happening in the test set. If the test set is about 10 it could easily all be one type. Maybe need to change the fold number

2022-01-27 20:30 UTC, aarmey commented
Try stratifying your folds: https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.StratifiedKFold.html

2022-01-28 20:27 UTC, aarmey approved these changes
Great! Merging.

2022-01-28 20:27 UTC, merged